// src/components/layout/AppShell.tsx
import { useState, type ReactNode } from 'react'
import { Outlet, useLocation, useNavigate } from 'react-router-dom'
import { LogOut, Menu, Shield, UserRound } from 'lucide-react'
import { Avatar, AvatarFallback } from '@/components/ui/avatar'
import { Button } from '@/components/ui/button'
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuLabel,
  DropdownMenuSeparator,
  DropdownMenuTrigger,
} from '@/components/ui/dropdown-menu'
import { Sheet, SheetContent, SheetTitle } from '@/components/ui/sheet'
import { ThemeMenu } from '@/components/common/ThemeMenu'
import { clearAuth, useAuth } from '@/lib/auth'
import { cn } from '@/lib/utils'

export interface NavItem {
  path: string
  label: string
  icon: ReactNode
}

function NavButton({
  item,
  active,
  onClick,
}: {
  item: NavItem
  active: boolean
  onClick: () => void
}) {
  return (
    <button
      type="button"
      onClick={onClick}
      className={cn(
        'flex w-full items-center gap-3 rounded-full px-4 py-2.5 text-sm font-medium transition-colors',
        active
          ? 'bg-secondary text-secondary-foreground'
          : 'text-muted-foreground hover:bg-accent hover:text-accent-foreground',
      )}
    >
      <span className="[&_svg]:size-5">{item.icon}</span>
      {item.label}
    </button>
  )
}

export function AppShell({ nav }: { nav: NavItem[] }) {
  const location = useLocation()
  const navigate = useNavigate()
  const auth = useAuth()
  const [sheetOpen, setSheetOpen] = useState(false)

  const isAdmin = auth.role === 'admin'
  const inAdmin = location.pathname.startsWith('/admin')
  const profilePath = inAdmin ? '/admin/profile' : '/user/profile'
  const active = nav.find((n) => location.pathname.startsWith(n.path)) ?? nav[0]
  const bottom = nav.slice(0, 4)
  const overflow = nav.slice(4)

  function go(path: string) {
    setSheetOpen(false)
    navigate(path)
  }
  function logout() {
    clearAuth()
    navigate('/')
  }

  const accountMenu = (
    <DropdownMenu>
      <DropdownMenuTrigger asChild>
        <Button variant="ghost" size="icon" aria-label="账户">
          <Avatar className="h-8 w-8">
            <AvatarFallback>{(auth.userName ?? '?').charAt(0)}</AvatarFallback>
          </Avatar>
        </Button>
      </DropdownMenuTrigger>
      <DropdownMenuContent align="end">
        <DropdownMenuLabel>{auth.userName ?? '账户'}</DropdownMenuLabel>
        <DropdownMenuSeparator />
        {isAdmin && (
          <DropdownMenuItem onClick={() => go(inAdmin ? '/user/commissions' : '/admin/commissions')}>
            {inAdmin ? <UserRound /> : <Shield />}
            {inAdmin ? '用户门户' : '管理员门户'}
          </DropdownMenuItem>
        )}
        <DropdownMenuItem onClick={() => go(profilePath)}>
          <UserRound />
          个人设置
        </DropdownMenuItem>
        <DropdownMenuSeparator />
        <DropdownMenuItem onClick={logout}>
          <LogOut />
          退出登录
        </DropdownMenuItem>
      </DropdownMenuContent>
    </DropdownMenu>
  )

  return (
    <div className="min-h-dvh bg-background">
      <header className="sticky top-0 z-40 border-b border-border bg-background/95 backdrop-blur">
        <div className="flex h-14 items-center gap-2 px-3 sm:px-4">
          <Button
            variant="ghost"
            size="icon"
            className="md:hidden"
            onClick={() => setSheetOpen(true)}
            aria-label="打开菜单"
          >
            <Menu />
          </Button>
          <span className="truncate text-base font-semibold sm:text-lg">{active?.label ?? ''}</span>
          <div className="ml-auto flex items-center gap-1">
            <ThemeMenu />
            {accountMenu}
          </div>
        </div>
      </header>

      <div className="mx-auto flex w-full max-w-7xl">
        <aside className="sticky top-14 hidden h-[calc(100dvh-3.5rem)] w-60 shrink-0 flex-col gap-1 overflow-y-auto border-r border-border p-3 md:flex">
          <div className="px-4 py-3 text-lg font-bold text-primary">代肝记录</div>
          <nav className="flex flex-1 flex-col gap-1">
            {nav.map((n) => (
              <NavButton
                key={n.path}
                item={n}
                active={location.pathname.startsWith(n.path)}
                onClick={() => go(n.path)}
              />
            ))}
          </nav>
        </aside>

        <main className="min-w-0 flex-1 px-3 pb-24 pt-4 sm:px-5 md:pb-8">
          <Outlet />
        </main>
      </div>

      <nav className="fixed inset-x-0 bottom-0 z-40 border-t border-border bg-background/95 backdrop-blur md:hidden">
        <div className="mx-auto flex max-w-lg items-stretch">
          {bottom.map((n) => {
            const isActive = location.pathname.startsWith(n.path)
            return (
              <button
                key={n.path}
                type="button"
                onClick={() => go(n.path)}
                className={cn(
                  'flex flex-1 flex-col items-center gap-0.5 py-2 pb-safe text-[11px]',
                  isActive ? 'text-primary' : 'text-muted-foreground',
                )}
              >
                <span className="[&_svg]:size-5">{n.icon}</span>
                <span className="truncate">{n.label}</span>
              </button>
            )
          })}
          {overflow.length > 0 && (
            <button
              type="button"
              onClick={() => setSheetOpen(true)}
              className="flex flex-1 flex-col items-center gap-0.5 py-2 pb-safe text-[11px] text-muted-foreground"
            >
              <Menu className="h-5 w-5" />
              <span>更多</span>
            </button>
          )}
        </div>
      </nav>

      <Sheet open={sheetOpen} onOpenChange={setSheetOpen}>
        <SheetContent side="left">
          <SheetTitle>导航</SheetTitle>
          <nav className="flex flex-1 flex-col gap-1 overflow-y-auto">
            {nav.map((n) => (
              <NavButton
                key={n.path}
                item={n}
                active={location.pathname.startsWith(n.path)}
                onClick={() => go(n.path)}
              />
            ))}
          </nav>
        </SheetContent>
      </Sheet>
    </div>
  )
}

// src/components/layout/AppShell.vue
<script setup lang="ts">
import { computed, ref } from 'vue'
import { RouterView, useRoute, useRouter } from 'vue-router'
import {
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuLabel,
  DropdownMenuPortal,
  DropdownMenuRoot,
  DropdownMenuSeparator,
  DropdownMenuTrigger,
} from 'reka-ui'
import { LogOut, Menu, Shield, UserRound } from '@lucide/vue'
import { adminNav, userNav, type NavItem } from '@/nav'
import Sheet from '@/components/ui/Sheet.vue'
import ThemeMenu from '@/components/layout/ThemeMenu.vue'
import ConfirmHost from '@/components/layout/ConfirmHost.vue'
import { useAuthStore } from '@/stores/auth'

const props = defineProps<{ nav: 'admin' | 'user' }>()
const route = useRoute()
const router = useRouter()
const auth = useAuthStore()

const nav = computed<NavItem[]>(() => (props.nav === 'admin' ? adminNav : userNav))
const inAdmin = computed(() => route.path.startsWith('/admin'))
const active = computed(() => nav.value.find((n) => route.path.startsWith(n.path)) ?? nav.value[0])
const bottom = computed(() => nav.value.slice(0, 4))
const overflow = computed(() => nav.value.slice(4))
const isAdmin = computed(() => auth.role === 'admin')
const profilePath = computed(() => (inAdmin.value ? '/admin/profile' : '/user/profile'))
const initial = computed(() => (auth.userName ?? '?').charAt(0))
const drawerOpen = ref(false)

function go(path: string) {
  drawerOpen.value = false
  router.push(path)
}
function logout() {
  auth.clear()
  router.push('/')
}
</script>

<template>
  <div class="min-h-dvh bg-bg text-text">
    <header
      class="sticky top-0 z-40 border-b border-border bg-bg/90 backdrop-blur supports-[backdrop-filter]:bg-bg/70"
    >
      <div class="mx-auto flex h-14 w-full max-w-7xl items-center gap-2 px-3 sm:px-5">
        <button
          type="button"
          class="inline-flex h-10 w-10 items-center justify-center rounded-md text-muted transition-colors hover:bg-surface-2 hover:text-text md:hidden"
          aria-label="打开菜单"
          @click="drawerOpen = true"
        >
          <Menu class="h-5 w-5" />
        </button>
        <span class="truncate text-base font-semibold tracking-tight sm:text-lg">
          {{ active?.label ?? '' }}
        </span>
        <div class="ml-auto flex items-center gap-1">
          <ThemeMenu />
          <DropdownMenuRoot>
            <DropdownMenuTrigger as-child>
              <button
                type="button"
                class="inline-flex h-10 w-10 items-center justify-center rounded-md transition-colors hover:bg-surface-2"
                aria-label="账户"
              >
                <span
                  class="flex h-8 w-8 items-center justify-center rounded-full bg-gradient-to-br from-accent-2 to-accent text-sm font-semibold text-accent-fg"
                >
                  {{ initial }}
                </span>
              </button>
            </DropdownMenuTrigger>
            <DropdownMenuPortal>
              <DropdownMenuContent
                align="end"
                :side-offset="6"
                class="z-50 w-52 rounded-xl border border-border bg-surface p-1 shadow-2xl data-[state=open]:anim-pop-in"
              >
                <DropdownMenuLabel class="truncate px-2 py-1.5 text-xs text-dim">
                  {{ auth.userName ?? '账户' }}
                </DropdownMenuLabel>
                <DropdownMenuSeparator class="my-1 h-px bg-border" />
                <DropdownMenuItem
                  v-if="isAdmin"
                  class="flex cursor-pointer items-center gap-2 rounded-md px-2 py-2 text-sm text-text outline-none data-[highlighted]:bg-surface-2"
                  @select="go(inAdmin ? '/user/commissions' : '/admin/commissions')"
                >
                  <component :is="inAdmin ? UserRound : Shield" class="h-4 w-4" />
                  {{ inAdmin ? '用户门户' : '管理员门户' }}
                </DropdownMenuItem>
                <DropdownMenuItem
                  class="flex cursor-pointer items-center gap-2 rounded-md px-2 py-2 text-sm text-text outline-none data-[highlighted]:bg-surface-2"
                  @select="go(profilePath)"
                >
                  <UserRound class="h-4 w-4" />
                  个人设置
                </DropdownMenuItem>
                <DropdownMenuSeparator class="my-1 h-px bg-border" />
                <DropdownMenuItem
                  class="flex cursor-pointer items-center gap-2 rounded-md px-2 py-2 text-sm text-danger outline-none data-[highlighted]:bg-surface-2"
                  @select="logout"
                >
                  <LogOut class="h-4 w-4" />
                  退出登录
                </DropdownMenuItem>
              </DropdownMenuContent>
            </DropdownMenuPortal>
          </DropdownMenuRoot>
        </div>
      </div>
    </header>

    <div class="mx-auto flex w-full max-w-7xl">
      <aside
        class="sticky top-14 hidden h-[calc(100dvh-3.5rem)] w-60 shrink-0 flex-col gap-1 overflow-y-auto border-r border-border p-3 md:flex"
      >
        <div class="flex items-center gap-2 px-3 py-3">
          <span class="h-2.5 w-2.5 rounded-full bg-accent shadow-[0_0_12px_var(--accent)]" />
          <span class="text-base font-bold tracking-tight">代肝记录</span>
        </div>
        <nav class="flex flex-1 flex-col gap-1">
          <button
            v-for="n in nav"
            :key="n.path"
            type="button"
            class="group relative flex items-center gap-3 rounded-lg px-3 py-2.5 text-sm font-medium transition-colors"
            :class="
              route.path.startsWith(n.path)
                ? 'bg-accent/10 text-accent'
                : 'text-muted hover:bg-surface-2 hover:text-text'
            "
            @click="go(n.path)"
          >
            <span
              v-if="route.path.startsWith(n.path)"
              class="absolute left-0 top-1/2 h-5 w-1 -translate-y-1/2 rounded-r-full bg-accent shadow-[0_0_10px_var(--accent)]"
            />
            <component :is="n.icon" class="h-5 w-5" />
            {{ n.label }}
          </button>
        </nav>
      </aside>

      <main class="min-w-0 flex-1 px-3 pb-24 pt-4 sm:px-5 md:pb-8">
        <RouterView v-slot="{ Component }">
          <Transition name="page" mode="out-in">
            <component :is="Component" :key="route.fullPath" />
          </Transition>
        </RouterView>
      </main>
    </div>

    <nav
      class="fixed inset-x-0 bottom-0 z-40 border-t border-border bg-bg/95 backdrop-blur md:hidden"
    >
      <div class="mx-auto flex max-w-lg items-stretch">
        <button
          v-for="n in bottom"
          :key="n.path"
          type="button"
          class="relative flex flex-1 flex-col items-center gap-0.5 py-2 pb-safe text-[11px] transition-colors"
          :class="route.path.startsWith(n.path) ? 'text-accent' : 'text-dim'"
          @click="go(n.path)"
        >
          <span
            v-if="route.path.startsWith(n.path)"
            class="absolute top-0 h-0.5 w-8 rounded-full bg-accent shadow-[0_0_10px_var(--accent)]"
          />
          <component :is="n.icon" class="h-5 w-5" />
          <span class="truncate">{{ n.label }}</span>
        </button>
        <button
          v-if="overflow.length"
          type="button"
          class="flex flex-1 flex-col items-center gap-0.5 py-2 pb-safe text-[11px] text-dim"
          @click="drawerOpen = true"
        >
          <Menu class="h-5 w-5" />
          <span>更多</span>
        </button>
      </div>
    </nav>

    <Sheet v-model:open="drawerOpen">
      <div class="flex flex-col gap-1">
        <button
          v-for="n in nav"
          :key="n.path"
          type="button"
          class="flex items-center gap-3 rounded-lg px-3 py-2.5 text-sm font-medium transition-colors"
          :class="
            route.path.startsWith(n.path)
              ? 'bg-accent/10 text-accent'
              : 'text-muted hover:bg-surface-2 hover:text-text'
          "
          @click="go(n.path)"
        >
          <component :is="n.icon" class="h-5 w-5" />
          {{ n.label }}
        </button>
      </div>
    </Sheet>

    <ConfirmHost />
  </div>
</template>
