// src/components/ui/Sheet.vue
<script setup lang="ts">
import { DialogContent, DialogOverlay, DialogPortal, DialogRoot, DialogTitle } from 'reka-ui'
import { X } from '@lucide/vue'
import { cn } from '@/lib/utils'

const open = defineModel<boolean>('open', { default: false })
const props = withDefaults(defineProps<{ side?: 'left' | 'right' }>(), { side: 'left' })
</script>

<template>
  <DialogRoot v-model:open="open">
    <DialogPortal>
      <DialogOverlay
        class="fixed inset-0 z-50 bg-black/70 data-[state=open]:anim-overlay-in data-[state=closed]:anim-overlay-out"
      />
      <DialogContent
        :class="
          cn(
            'group fixed top-0 z-50 flex h-full w-72 flex-col border-border bg-surface shadow-2xl outline-none',
            props.side === 'right'
              ? 'right-0 border-l data-[state=open]:anim-slide-left'
              : 'left-0 border-r data-[state=open]:anim-slide-right',
          )
        "
      >
        <DialogTitle class="sr-only">菜单</DialogTitle>
        <div class="flex items-center justify-between border-b border-border p-4">
          <slot name="title"><span class="text-sm font-semibold text-muted">菜单</span></slot>
          <button
            type="button"
            class="rounded-md p-1 text-dim transition-colors hover:bg-surface-2 hover:text-text"
            aria-label="关闭"
            @click="open = false"
          >
            <X class="h-4 w-4" />
          </button>
        </div>
        <div class="min-h-0 flex-1 overflow-y-auto p-3"><slot /></div>
      </DialogContent>
    </DialogPortal>
  </DialogRoot>
</template>

// src/components/ui/sheet.tsx
import * as DialogPrimitive from '@radix-ui/react-dialog'
import { X } from 'lucide-react'
import type { ComponentProps } from 'react'
import { cn } from '@/lib/utils'

export const Sheet = DialogPrimitive.Root
export const SheetTrigger = DialogPrimitive.Trigger
export const SheetClose = DialogPrimitive.Close

type Side = 'left' | 'right' | 'top' | 'bottom'

const sideClasses: Record<Side, string> = {
  left: 'left-0 top-0 h-full w-72 border-r data-[state=open]:translate-x-0',
  right: 'right-0 top-0 h-full w-72 border-l',
  top: 'top-0 left-0 w-full border-b',
  bottom: 'bottom-0 left-0 w-full border-t',
}

export function SheetContent({
  className,
  children,
  side = 'left',
  ...props
}: ComponentProps<typeof DialogPrimitive.Content> & { side?: Side }) {
  return (
    <DialogPrimitive.Portal>
      <DialogPrimitive.Overlay className="fixed inset-0 z-50 bg-black/50" />
      <DialogPrimitive.Content
        className={cn(
          'fixed z-50 flex flex-col gap-4 border-border bg-background p-4 shadow-xl',
          sideClasses[side],
          className,
        )}
        {...props}
      >
        {children}
        <DialogPrimitive.Close className="absolute right-3 top-3 rounded-full p-1 text-muted-foreground hover:bg-accent">
          <X className="h-4 w-4" />
          <span className="sr-only">关闭</span>
        </DialogPrimitive.Close>
      </DialogPrimitive.Content>
    </DialogPrimitive.Portal>
  )
}

export function SheetTitle({ className, ...props }: ComponentProps<typeof DialogPrimitive.Title>) {
  return (
    <DialogPrimitive.Title
      className={cn('text-sm font-semibold text-muted-foreground', className)}
      {...props}
    />
  )
}
